### ISSUE TITLE
Enabling profiling via env variable in Serverless Framework not working

### ISSUE THREAD

**Issue by austinhuminski** [iopipe/iopipe-js-profiler#64] opened 2019-07-09 18:43 UTC
When settings `IOPIPE_ENABLE_PROFILER: true` in serverless.yml file profiling is not getting enabled and I get an error in my CW logs with debug on

Node10
serverless-iopipe-layers: 0.3.3
arn:aws:lambda:us-east-1:146318645305:layer:IOpipeNodeJS10:1

```
2019-07-09T16:09:30.606Z    8013aca9-2f0e-4702-9aee-6954d5edc30a    ERROR    TypeError: Cannot read property 'getFileUploadMeta' of undefined
 at ProfilerPlugin.getFileUploadMeta (/opt/nodejs/node_modules/@iopipe/profiler/dist/index.js:124:23)
 at ProfilerPlugin.preInvoke (/opt/nodejs/node_modules/@iopipe/profiler/dist/index.js:96:28)
 at /opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1984:30
 at Array.map (<anonymous>)
 at IOpipeWrapperClass._callee3$ (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1980:44)
 at tryCatch (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:2244:40)
 at Generator.invoke [as _invoke] (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:2478:22)
 at Generator.prototype.(anonymous function) [as next] (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:2296:21)
 at step (/opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1034:30)
 at /opt/nodejs/node_modules/@iopipe/core/dist/iopipe.js:1052:14
```

**Comment by mrickard** [comment] 2019-07-09 19:47
Potential duplicate of #45 --it's the same error.  Is this just on Node 10, or with Node 8 as well?

**Comment by kolanos** [comment] 2019-07-09 20:11
@mrickard Not seeing this error in the issue referenced? May be related, @austinhuminski reports this error is being seen in `us-east-1` and `eu-central-1`, so not a local invoke like the issue you referenced.

**Comment by kolanos** [comment] 2019-07-09 20:15
`'getFileUploadMeta' of undefined
 at ProfilerPlugin.getFileUploadMeta (/opt/nodejs/node_modules/@iopipe/profiler/dist/index.js:124:23)` suggests a bug in the upload/signing process or a possible incompatibility between core and the profiler plugin.

**Comment by mrickard** [comment] 2019-07-09 20:21
@kolanos True--that issue's a silent error, while I was seeing local invocations logging an error to stdout. Part of the problem there appears to be that the import of util from -core is undefined. In jest tests of -profile, util is imported correctly, but on inclusion in a project, -profile isn't able to import the separately-included -core.  This can happen when there's a circular dependency, and while this isn't *circular*, as far as I can tell, the problem does seem to be the import. 

Locally, it seems that the profile import of core does not throw this error if the function is using iopipe-js 1.15, but I've seen the error under 1.14.

**Comment by austinhuminski** [comment] 2019-07-09 21:09
Tried this without the serverless-iopipe-layers plugin and got the same error. Used the @iopipe/iopipe method on both Node 10 and Node 8 with the same results.

**Comment by mrickard** [comment] 2019-07-09 21:40
@austinhuminski Interesting--I'm building a couple layers functions and I'll test them against non-layer as well.

**Comment by kolanos** [comment] 2019-07-11 00:06
@mrickard Did #65 have any effect here?

**Comment by mrickard** [comment] 2019-07-11 00:39
@kolanos Unfortunately no! I did check that, but the error's still being thrown to the console.  It's related to dependencies, I think, so I'm trying to configure a circular dependency check in ESLint.

**Closed** 2019-07-12 14:51 UTC
